name: Deploy 🌌

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: panpipe-team/frontend-server

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write


    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Registry 🔐
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image 🧱 && 🚀
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
          push: true

  deploy:
    needs: push-to-registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull docker image and run it ☝️
        uses: appleboy/ssh-action@v0.1.5
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          FRONTEND_SERVER_PORT: ${{ secrets.FRONTEND_SERVER_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ env.GHCR_USERNAME}} --password-stdin
            docker image pull ghcr.io/${{ env.IMAGE_NAME }}:latest
            docker container stop panpipe-frontend-server
            docker container remove panpipe-frontend-server
            docker container run -d --name panpipe-frontend-server -p ${{ env.FRONTEND_SERVER_PORT }}:8080 ${{ env.IMAGE_NAME}}
